### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by appst** [Clarionos/clarion#48]
following the build instructions on a clean 20.04.1 I get lots of warning that eventually lead to the following...

    default: [ 96%] Linking CXX static library libclarion-net.a
    default: [ 96%] Built target clarion-net
    default: Scanning dependencies of target clarionc
    default: [ 97%] Building CXX object programs/clarionc/CMakeFiles/clarionc.dir/main.cpp.o
    default: [ 98%] Linking CXX executable /home/picasso/clarion/build/clarionc
    default: [ 98%] Built target clarionc
    default: [100%] Linking CXX executable /home/picasso/clarion/build/clio-tests
    default: [100%] Built target clio-tests
    default: [ 81%] No install step for 'native'
    default: [ 87%] Completed 'native'
    default: [ 87%] Built target native
    default: make: *** [Makefile:84: all] Error 2
    default: Test project /home/picasso/clarion/build
    default:     Start 1: n-clio-tests
    default:     Start 2: w-clio-tests
    default:     Start 3: w-test-clintrinsics
    default: 1/3 Test #2: w-clio-tests .....................
    default: ***Failed    0.04 sec
    default: 2/3 Test #3: w-test-clintrinsics ..............
    default: ***Failed    0.04 sec
    default: 3/3 Test #1: n-clio-tests .....................
    default:    Passed    0.60 sec
    default:
    default: 33% tests passed, 2 tests failed out of 3
    default:
    default: Total Test time (real) =   0.60 sec
    default:
    default: The following tests FAILED:
    default:      2 - w-clio-tests (Failed)
    default:      3 - w-test-clintrinsics (Failed)
    default: Errors while running CTest
    default: internal/modules/cjs/loader.js:883
    default:   throw err;
    default:   ^
    default:
    default: Error: Cannot find module '/home/picasso/clarion/build/dist/clariond'
    default:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    default:     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    default:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    default:     at internal/main/run_main_module.js:17:47 {
    default:   code: 'MODULE_NOT_FOUND',
    default:   requireStack: []
    default: }
    default: [ 12%] Performing build step for 'wasm'
    default: [ 66%] Built target clintrinsics
    default: [ 70%] Building CXX object tests/clio/CMakeFiles/clio-tests.dir/flat_views.cpp.obj
    default: /home/picasso/clarion/tests/clio/flat_views.cpp

ask if you would like the complete output.
thanks

**Comment by faddat** [comment]
I had similar issues, and I solved them by building.... everything:

```Dockerfile
FROM faddat/archlinux

COPY . /clarion

ENV WASI_SDK_PREFIX=/opt/wasi-sdk

RUN pacman -Syyu --noconfirm base-devel binaryen cmake curl git boost git openssl gmp clang ninja yarn python

RUN git clone https://github.com/WebAssembly/wasi-sdk/ --branch wasi-sdk-12 --recursive

RUN cd wasi-sdk && \
        make -j24 && \
        cp -r build/install/opt/wasi-sdk /opt

RUN cd /clarion && \
                mkdir build && \
                cd build && \
                cmake -DCMAKE_BUILD_TYPE=Release .. && \
                make -j$(nproc) && \
                ctest -j$(nproc) && \
                mkdir -p clariondata
```
